= geOrchestra Gateway
:toc:
:toc-placement!:


toc::[]

== Management endpoints

geOrchestra Gateway exposes standard https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html[Spring Boot Actuator] management endpoints.

The management endpoints are exposed on a separate port than the application itself
for security reasons, since this service will most of the time be a front service.

The default port is `8090`, so when running locally, management endpoints will be
available at http://localhost:8090/actuator/

The default configuration exposes almost everything with the following configuration,
which can be overridden in georchestra datadirectory's `gateway/gateway.yaml`:

```
management:
  server:
    port: 8090
  info:
    build.enabled: true
    java.enabled: true
    env.enabled: true
    git:
      enabled: true
      mode: full
  endpoints:
    enabled-by-default: true
    web.exposure.include: "*"
  endpoint:
    info.enabled: true
    metrics.enabled: true
    shutdown.enabled: true
    health:
      enabled: true
      probes.enabled: true
      show-details: always
  metrics:
    binders:
      processor.enabled: true
      uptime.enabled: true
      jvm.enabled: true
    enable.all: true
    enable.jvm: true
```

== Common management end points

=== Health check

http://localhost:8090/actuator/health

```
{
  "status": "UP",
  "components": {
    "diskSpace": {
      "status": "UP",
      "details": {
        "total": 879318138880,
        "free": 744965537792,
        "threshold": 10485760,
        "exists": true
      }
    },
    "livenessState": {
      "status": "UP"
    },
    "ping": {
      "status": "UP"
    },
    "readinessState": {
      "status": "UP"
    },
    "refreshScope": {
      "status": "UP"
    }
  },
  "groups": [
    "liveness",
    "readiness"
  ]
}
```

=== liveness, and readiness probes

Mostly useful in kubernetes environments, the `liveness` and `readiness` probes
are exposed at:

http://localhost:8090/actuator/health/liveness

```
{"status": "UP"}
```

http://localhost:8090/actuator/health/readiness

```
{"status": "UP"}
```

=== metrics

A number of metrics are automatically exposed for monitoring by external systems at

http://localhost:8090/actuator/metrics

```

  "names": [
    "application.ready.time",
    "application.started.time",
    "disk.free",
    "disk.total",
    "executor.active",
    "executor.completed",
    "executor.pool.core",
    "executor.pool.max",
    "executor.pool.size",
    "executor.queue.remaining",
    "executor.queued",
    "http.server.requests",
    "jvm.buffer.count",
    "jvm.buffer.memory.used",
    "jvm.buffer.total.capacity",
    "jvm.classes.loaded",
    "jvm.classes.unloaded",
    "jvm.gc.live.data.size",
    "jvm.gc.max.data.size",
    "jvm.gc.memory.allocated",
    "jvm.gc.memory.promoted",
    "jvm.gc.overhead",
    "jvm.gc.pause",
    "jvm.memory.committed",
    "jvm.memory.max",
    "jvm.memory.usage.after.gc",
    "jvm.memory.used",
    "jvm.threads.daemon",
    "jvm.threads.live",
    "jvm.threads.peak",
    "jvm.threads.states",
    "logback.events",
    "process.cpu.usage",
    "process.files.max",
    "process.files.open",
    "process.start.time",
    "process.uptime",
    "spring.cloud.gateway.routes.count",
    "system.cpu.count",
    "system.cpu.usage",
    "system.load.average.1m"
  ]
}
```

Accessing a specific metric is a matter of appending the metric name to the URL,
for example:

http://localhost:8090/actuator/metrics/process.cpu.usage

```
{
  "name": "process.cpu.usage",
  "description": "The \"recent cpu usage\" for the Java Virtual Machine process",
  "baseUnit": null,
  "measurements": [
    {
      "statistic": "VALUE",
      "value": 0.0
    }
  ],
  "availableTags": [
    
  ]
}
```