= geOrchestra Gateway
:toc:
:toc-placement!:


toc::[]

== Management endpoints

geOrchestra Gateway exposes standard https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html[Spring Boot Actuator] management endpoints.

The management endpoints are exposed on a separate port than the application itself
for security reasons, since this service will most of the time be a front service.

The default port is `8090`, so when running locally, management endpoints will be
available at http://localhost:8090/actuator/

The default configuration exposes almost everything with the following configuration,
which can be overridden in georchestra datadirectory's `gateway/gateway.yaml`:

```
management:
  server:
    port: 8090
  info:
    build.enabled: true
    java.enabled: true
    env.enabled: true
    git:
      enabled: true
      mode: full
  endpoints:
    enabled-by-default: true
    web.exposure.include: "*"
  endpoint:
    info.enabled: true
    metrics.enabled: true
    shutdown.enabled: true
    health:
      enabled: true
      probes.enabled: true
      show-details: always
  metrics:
    binders:
      processor.enabled: true
      uptime.enabled: true
      jvm.enabled: true
    enable.all: true
    enable.jvm: true
```

== Common management end points

=== Info

The `info` endpoint exposes application build information.

http://localhost:8090/actuator/info

```
  "component": "Gateway Server",
  "instance-id": "gateway-service:192.168.0.21:8080",
  "git": {
    "branch": "main",
    "commit": {
      "id": "4367145",
      "time": "2022-06-27T13:08:31Z"
    }
  },
  "build": {
    "artifact": "georchestra-gateway",
    "name": "gateway",
    "time": "2022-06-27T13:16:16.741Z",
    "version": "21.0-RC1",
    "group": "org.georchestra"
  },
  "java": {
    "vendor": "Eclipse Adoptium",
    "version": "17.0.2",
    "runtime": {
      "name": "OpenJDK Runtime Environment",
      "version": "17.0.2+8"
    },
    "jvm": {
      "name": "OpenJDK 64-Bit Server VM",
      "vendor": "Eclipse Adoptium",
      "version": "17.0.2+8"
    }
  }
}
```

Additional git information can be enabled. To do so, configure the following
property: `management.info.git.mode=full` (the default is `simple`), either 
in `gateway.yaml` or as an environment variable, following spring-boot's 
standard externalized configuration conventions.

This will result in extended git info like in the following example:

```
{
  "component": "Gateway Server",
  "instance-id": "gateway-service:192.168.0.21:8080",
  "git": {
    "local": {
      "branch": {
        "ahead": "2",
        "behind": "0"
      }
    },
    "commit": {
      "id": {
        "describe-short": "v21.0-RC1",
        "abbrev": "4367145",
        "full": "436714527af04cde2bcd09f51f73545ac86ee02d",
        "describe": "v21.0-RC1"
      },
      "message": {
        "short": "Set version to 21.0-RC1",
        "full": "Set version to 21.0-RC1"
      },
      "user": {
        "name": "Gabriel Roldan",
        "email": "gabriel.roldan@test.com"
      },
      "author": {
        "time": "2022-06-27T10:08:31-0300"
      },
      "committer": {
        "time": "2022-06-27T10:08:31-0300"
      },
      "time": "2022-06-27T13:08:31Z"
    },
    "branch": "main",
    "build": {
      "time": "2022-06-27T13:11:12Z",
      "version": "21.0-RC1",
      "host": "lilith",
      "user": {
        "name": "Gabriel Roldan",
        "email": "gabriel.roldan@test.com"
      }
    },
    "tags": "v21.0-RC1",
    "total": {
      "commit": {
        "count": "90"
      }
    },
    "closest": {
      "tag": {
        "commit": {
          "count": "0"
        },
        "name": "v21.0-RC1"
      }
    },
    "remote": {
      "origin": {
        "url": "Unknown"
      }
    },
    "dirty": "false"
  },
  ...
}
```

=== Health check

http://localhost:8090/actuator/health

```
{
  "status": "UP",
  "components": {
    "diskSpace": {
      "status": "UP",
      "details": {
        "total": 879318138880,
        "free": 744965537792,
        "threshold": 10485760,
        "exists": true
      }
    },
    "livenessState": {
      "status": "UP"
    },
    "ping": {
      "status": "UP"
    },
    "readinessState": {
      "status": "UP"
    },
    "refreshScope": {
      "status": "UP"
    }
  },
  "groups": [
    "liveness",
    "readiness"
  ]
}
```

=== liveness, and readiness probes

Mostly useful in kubernetes environments, the `liveness` and `readiness` probes
are exposed at:

http://localhost:8090/actuator/health/liveness

```
{"status": "UP"}
```

http://localhost:8090/actuator/health/readiness

```
{"status": "UP"}
```

=== metrics

A number of metrics are automatically exposed for monitoring by external systems at

http://localhost:8090/actuator/metrics

```

  "names": [
    "application.ready.time",
    "application.started.time",
    "disk.free",
    "disk.total",
    "executor.active",
    "executor.completed",
    "executor.pool.core",
    "executor.pool.max",
    "executor.pool.size",
    "executor.queue.remaining",
    "executor.queued",
    "http.server.requests",
    "jvm.buffer.count",
    "jvm.buffer.memory.used",
    "jvm.buffer.total.capacity",
    "jvm.classes.loaded",
    "jvm.classes.unloaded",
    "jvm.gc.live.data.size",
    "jvm.gc.max.data.size",
    "jvm.gc.memory.allocated",
    "jvm.gc.memory.promoted",
    "jvm.gc.overhead",
    "jvm.gc.pause",
    "jvm.memory.committed",
    "jvm.memory.max",
    "jvm.memory.usage.after.gc",
    "jvm.memory.used",
    "jvm.threads.daemon",
    "jvm.threads.live",
    "jvm.threads.peak",
    "jvm.threads.states",
    "logback.events",
    "process.cpu.usage",
    "process.files.max",
    "process.files.open",
    "process.start.time",
    "process.uptime",
    "spring.cloud.gateway.routes.count",
    "system.cpu.count",
    "system.cpu.usage",
    "system.load.average.1m"
  ]
}
```

Accessing a specific metric is a matter of appending the metric name to the URL,
for example:

http://localhost:8090/actuator/metrics/process.cpu.usage

```
{
  "name": "process.cpu.usage",
  "description": "The \"recent cpu usage\" for the Java Virtual Machine process",
  "baseUnit": null,
  "measurements": [
    {
      "statistic": "VALUE",
      "value": 0.0
    }
  ],
  "availableTags": [
    
  ]
}
```