== Adding additional roles

The Gateway sends a `sec-roles` HTTP request header to the backend services
with the role names provided by the authentication provider.

Sometimes, these roles are insufficient as some services may require additional
or different role names.

For example, let's say the OpenID Connect provider gives us a role namded `GDI.ADMIN`, and 
we want users with that role to be GeoServer administrators, which requires the user to belong to the `ROLE_ADMINISTRATOR` role.

Hence, we can tell the Gateway to add the `ROLE_ADMINISTRATOR` role to any user logged in
with the `GDI.ADMIN` role.

This can be configured in the geOrchestra data directory's `gateway/gateway.yaml` file. Though
for the sake of separation of concerns across config files, we're using the `gateway/roles-mappings.yml` file, which is imported from `gateway/gateway.yml`.

This configuration file allows to extend the list of security role names
assigned to a user, from the role names extracted by the authentication
provider (e.g. LDAP, Oauth2, OpenID Connect).

Limited regular expression support: only the `*` character is allowed
as a wildcard on a source role name. For example, the following mapping
will add the `ROLE_USER` role to all authenticated users that already
have any role name starting with `ROLE_GP.GDI.`

Note that for the key names (source roles) to include special characters,
you must use the format '[role.name.*]' for the literal string role.name.*
to be interpreted correctly.
 
[source,yaml]
----
georchestra:
  gateway:
    role-mappings:
      '[ROLE_GP.GDI.*]'
        - ROLE_USER
----
 
If an authentication provider role name matches multiple mappings,
all the matching additional roles will be appended. For example, the
following mappings will add both `ROLE_USER` and `ROLE_ADMINISTRATOR`
to a user with role `ROLE_GP.GDI.ADMINISTRATOR`, but only `ROLE_USER`
to any other with a role starting with `ROLE_GP.GDI.`:

[source,yaml]
----
georchestra:
  gateway:
    role-mappings:
      '[ROLE_GP.GDI.*]':
        - ROLE_USER
      '[ROLE_GP.GDI.ADMINISTRATOR]':
        - ROLE_ADMINISTRATOR
----
